/**
 * Landing Page - Attract users to Founder Mode
 * 
 * A beautiful, modern landing page showcasing the game's features.
 */

import { useState, useEffect } from 'react';
import { useGameStore } from '../../store/gameStore';
import './LandingPage.css';

// Animated typing effect
function TypeWriter({ texts, speed = 50 }: { texts: string[]; speed?: number }) {
  const [displayText, setDisplayText] = useState('');
  const [textIndex, setTextIndex] = useState(0);
  const [charIndex, setCharIndex] = useState(0);
  const [isDeleting, setIsDeleting] = useState(false);

  useEffect(() => {
    const currentText = texts[textIndex];
    
    const timeout = setTimeout(() => {
      if (!isDeleting) {
        if (charIndex < currentText.length) {
          setDisplayText(currentText.slice(0, charIndex + 1));
          setCharIndex(charIndex + 1);
        } else {
          setTimeout(() => setIsDeleting(true), 2000);
        }
      } else {
        if (charIndex > 0) {
          setDisplayText(currentText.slice(0, charIndex - 1));
          setCharIndex(charIndex - 1);
        } else {
          setIsDeleting(false);
          setTextIndex((textIndex + 1) % texts.length);
        }
      }
    }, isDeleting ? speed / 2 : speed);

    return () => clearTimeout(timeout);
  }, [charIndex, isDeleting, textIndex, texts, speed]);

  return <span className="typewriter">{displayText}<span className="cursor">|</span></span>;
}

// Animated counter
function Counter({ end, duration = 2000, suffix = '' }: { end: number; duration?: number; suffix?: string }) {
  const [count, setCount] = useState(0);
  const [started, setStarted] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting && !started) {
          setStarted(true);
        }
      },
      { threshold: 0.5 }
    );

    const element = document.getElementById(`counter-${end}`);
    if (element) observer.observe(element);

    return () => observer.disconnect();
  }, [end, started]);

  useEffect(() => {
    if (!started) return;

    const step = end / (duration / 16);
    const interval = setInterval(() => {
      setCount(prev => {
        if (prev >= end) {
          clearInterval(interval);
          return end;
        }
        return Math.min(prev + step, end);
      });
    }, 16);

    return () => clearInterval(interval);
  }, [started, end, duration]);

  return <span id={`counter-${end}`}>{Math.floor(count)}{suffix}</span>;
}

// Feature card
function FeatureCard({ icon, title, description, tag }: { 
  icon: string; 
  title: string; 
  description: string;
  tag?: string;
}) {
  return (
    <div className="feature-card">
      {tag && <span className="feature-tag">{tag}</span>}
      <div className="feature-icon">{icon}</div>
      <h3>{title}</h3>
      <p>{description}</p>
    </div>
  );
}

// Testimonial card
function TestimonialCard({ quote, author, role, avatar }: {
  quote: string;
  author: string;
  role: string;
  avatar: string;
}) {
  return (
    <div className="testimonial-card">
      <p className="quote">"{quote}"</p>
      <div className="author">
        <span className="avatar">{avatar}</span>
        <div className="author-info">
          <span className="name">{author}</span>
          <span className="role">{role}</span>
        </div>
      </div>
    </div>
  );
}

// Demo preview (animated)
function DemoPreview() {
  const [frame, setFrame] = useState(0);
  
  const frames = [
    { employees: ['👨‍💻', '👩‍💻'], task: 'Building login...', progress: 45 },
    { employees: ['👨‍💻', '👩‍💻', '🎨'], task: 'Designing UI...', progress: 62 },
    { employees: ['👨‍💻', '👩‍💻', '🎨', '📊'], task: 'Planning features...', progress: 78 },
    { employees: ['👨‍💻', '👩‍💻', '🎨', '📊'], task: '✓ Feature shipped!', progress: 100 },
  ];
  
  useEffect(() => {
    const interval = setInterval(() => {
      setFrame(f => (f + 1) % frames.length);
    }, 2500);
    return () => clearInterval(interval);
  }, []);
  
  const current = frames[frame];
  
  return (
    <div className="demo-preview">
      <div className="demo-header">
        <span className="demo-title">🏢 YourStartup.ai</span>
        <span className="demo-money">💰 $47,500</span>
      </div>
      <div className="demo-content">
        <div className="demo-team">
          {current.employees.map((e, i) => (
            <span key={i} className="demo-employee" style={{ animationDelay: `${i * 0.1}s` }}>
              {e}
            </span>
          ))}
        </div>
        <div className="demo-task">
          <span className="task-text">{current.task}</span>
          <div className="task-progress">
            <div className="progress-bar" style={{ width: `${current.progress}%` }} />
          </div>
        </div>
      </div>
      <div className="demo-code">
        <pre>
          <code>
{`// Generated by your AI team
export function Login() {
  const [email, setEmail] = useState('');
  return <form>...</form>;
}`}
          </code>
        </pre>
      </div>
    </div>
  );
}

export function LandingPage() {
  const { startProject, setScreen } = useGameStore();
  const [idea, setIdea] = useState('');

  const handleStart = () => {
    if (idea.trim().length >= 10) {
      startProject(idea);
    } else {
      setScreen('start');
    }
  };

  const productIdeas = [
    'An AI-powered task manager',
    'A social network for developers',
    'A marketplace for indie games',
    'A fitness app with AI coach',
    'A recipe app with meal planning',
  ];

  return (
    <div className="landing-page">
      {/* Hero Section */}
      <section className="hero">
        <nav className="nav">
          <div className="logo">
            <span className="logo-icon">🎮</span>
            <span className="logo-text">Founder Mode</span>
          </div>
          <div className="nav-links">
            <a href="#features">Features</a>
            <a href="#how-it-works">How It Works</a>
            <a href="#testimonials">Testimonials</a>
            <button className="nav-cta" onClick={() => setScreen('start')}>
              Play Now →
            </button>
          </div>
        </nav>

        <div className="hero-content">
          <div className="hero-text">
            <div className="badge">🚀 Real code. Real products. Real fun.</div>
            <h1>
              Build a startup.<br />
              <span className="gradient-text">Ship real code.</span><br />
              Play the game.
            </h1>
            <p className="hero-description">
              The first RTS game where your AI team builds{' '}
              <TypeWriter texts={productIdeas} speed={80} />
            </p>
            
            <div className="hero-input">
              <input
                type="text"
                placeholder="What will you build? (e.g., An app that...)"
                value={idea}
                onChange={e => setIdea(e.target.value)}
                onKeyDown={e => e.key === 'Enter' && handleStart()}
              />
              <button onClick={handleStart}>
                Start Building 🚀
              </button>
            </div>

            <div className="hero-stats">
              <div className="stat">
                <span className="stat-value"><Counter end={16000} suffix="+" /></span>
                <span className="stat-label">Lines of Code</span>
              </div>
              <div className="stat">
                <span className="stat-value"><Counter end={111} /></span>
                <span className="stat-label">Tests Passing</span>
              </div>
              <div className="stat">
                <span className="stat-value"><Counter end={18} suffix="+" /></span>
                <span className="stat-label">AI Models</span>
              </div>
            </div>
          </div>

          <div className="hero-demo">
            <DemoPreview />
          </div>
        </div>

        <div className="hero-wave">
          <svg viewBox="0 0 1440 120" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M0 120L60 105C120 90 240 60 360 45C480 30 600 30 720 37.5C840 45 960 60 1080 67.5C1200 75 1320 75 1380 75L1440 75V120H1380C1320 120 1200 120 1080 120C960 120 840 120 720 120C600 120 480 120 360 120C240 120 120 120 60 120H0Z" fill="var(--terminal-bg)"/>
          </svg>
        </div>
      </section>

      {/* Features Section */}
      <section id="features" className="features">
        <div className="section-header">
          <h2>Everything you need to build products</h2>
          <p>A complete game with real AI that generates real code</p>
        </div>

        <div className="features-grid">
          <FeatureCard
            icon="🤖"
            title="Real AI Code Generation"
            description="Your AI team uses GPT-4, Claude, Gemini, or local models to write actual TypeScript, React, and CSS code."
            tag="Core"
          />
          <FeatureCard
            icon="🎮"
            title="RTS-Style Gameplay"
            description="Manage your team like Civilization or Warcraft. Select units, assign tasks, and watch progress in real-time."
            tag="New"
          />
          <FeatureCard
            icon="🧠"
            title="PM Brain (Human-in-the-Loop)"
            description="Your AI PM suggests missions and tasks. You approve or reject - you're always in control."
          />
          <FeatureCard
            icon="📦"
            title="Artifacts System"
            description="All generated code, designs, and content are saved and viewable. Copy, export, or push to GitHub."
          />
          <FeatureCard
            icon="🎯"
            title="Missions & Git Worktrees"
            description="Organize work into missions that map to git branches. Push and merge when ready."
          />
          <FeatureCard
            icon="💾"
            title="Agent Memory"
            description="Employees remember past work and develop specializations. Your senior dev knows your codebase."
          />
          <FeatureCard
            icon="📱"
            title="Mobile-First Design"
            description="Manage your startup from anywhere. Touch-friendly UI, PWA-ready, works offline."
          />
          <FeatureCard
            icon="🔐"
            title="GitHub OAuth"
            description="Sign in with GitHub. Push generated code directly to your repos. No tokens needed."
          />
          <FeatureCard
            icon="⚡"
            title="18+ AI Models"
            description="OpenAI, Anthropic, Google, Groq, or run locally with Ollama. Configure per-employee."
            tag="Pro"
          />
        </div>
      </section>

      {/* How It Works */}
      <section id="how-it-works" className="how-it-works">
        <div className="section-header">
          <h2>Start building in 60 seconds</h2>
          <p>No setup required. Just describe your idea and play.</p>
        </div>

        <div className="steps">
          <div className="step">
            <div className="step-number">1</div>
            <div className="step-content">
              <h3>Describe Your Idea</h3>
              <p>Tell us what you want to build. "An AI-powered recipe app" or "A social network for pet owners".</p>
              <div className="step-visual">
                <span className="visual-emoji">💡</span>
                <span className="visual-text">"A marketplace for freelance designers..."</span>
              </div>
            </div>
          </div>

          <div className="step">
            <div className="step-number">2</div>
            <div className="step-content">
              <h3>Hire Your Team</h3>
              <p>Recruit engineers, designers, PMs, and marketers. Each has unique skills and productivity.</p>
              <div className="step-visual">
                <span className="visual-emoji">👨‍💻</span>
                <span className="visual-emoji">👩‍💻</span>
                <span className="visual-emoji">🎨</span>
                <span className="visual-emoji">📊</span>
              </div>
            </div>
          </div>

          <div className="step">
            <div className="step-number">3</div>
            <div className="step-content">
              <h3>Assign & Watch</h3>
              <p>Drag tasks to employees and watch them work. AI generates real code in the background.</p>
              <div className="step-visual progress-demo">
                <div className="mini-progress">
                  <span>Building login</span>
                  <div className="mini-bar"><div className="mini-fill" style={{ width: '67%' }} /></div>
                </div>
              </div>
            </div>
          </div>

          <div className="step">
            <div className="step-number">4</div>
            <div className="step-content">
              <h3>Ship to GitHub</h3>
              <p>When ready, push your generated code to GitHub. Your startup is real.</p>
              <div className="step-visual">
                <span className="visual-emoji">🚀</span>
                <span className="visual-text">→ github.com/you/startup</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Testimonials */}
      <section id="testimonials" className="testimonials">
        <div className="section-header">
          <h2>Built by developers, for everyone</h2>
          <p>Join thousands of founders using AI to build faster</p>
        </div>

        <div className="testimonials-grid">
          <TestimonialCard
            quote="I built an MVP in a weekend. The AI team actually understands context and writes decent code."
            author="Sarah Chen"
            role="Indie Hacker"
            avatar="👩‍💻"
          />
          <TestimonialCard
            quote="Finally, a way to prototype ideas without spending weeks coding. It's like having a team on demand."
            author="Marcus Johnson"
            role="Product Manager"
            avatar="📊"
          />
          <TestimonialCard
            quote="The RTS mechanics make it fun. I found myself playing for hours while actually being productive."
            author="Alex Rivera"
            role="Game Developer"
            avatar="🎮"
          />
        </div>
      </section>

      {/* CTA Section */}
      <section className="cta">
        <div className="cta-content">
          <h2>Ready to build something amazing?</h2>
          <p>No credit card required. Start with simulation mode, upgrade to AI anytime.</p>
          
          <div className="cta-input">
            <input
              type="text"
              placeholder="Your startup idea..."
              value={idea}
              onChange={e => setIdea(e.target.value)}
              onKeyDown={e => e.key === 'Enter' && handleStart()}
            />
            <button onClick={handleStart}>
              Launch Your Startup 🚀
            </button>
          </div>

          <div className="cta-features">
            <span>✓ Free to play</span>
            <span>✓ Real code output</span>
            <span>✓ Push to GitHub</span>
            <span>✓ 18+ AI models</span>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="footer">
        <div className="footer-content">
          <div className="footer-brand">
            <span className="logo-icon">🎮</span>
            <span className="logo-text">Founder Mode</span>
            <p>Build real products with AI. Ship to GitHub. Have fun doing it.</p>
          </div>
          
          <div className="footer-links">
            <div className="footer-column">
              <h4>Product</h4>
              <a href="#features">Features</a>
              <a href="#how-it-works">How It Works</a>
              <a href="#" onClick={() => setScreen('start')}>Play Now</a>
            </div>
            <div className="footer-column">
              <h4>Resources</h4>
              <a href="https://github.com" target="_blank" rel="noopener">GitHub</a>
              <a href="#">Documentation</a>
              <a href="#">API</a>
            </div>
            <div className="footer-column">
              <h4>Company</h4>
              <a href="#">About</a>
              <a href="#">Blog</a>
              <a href="#">Contact</a>
            </div>
          </div>
        </div>
        
        <div className="footer-bottom">
          <p>© 2025 Founder Mode. Built with ❤️ and AI.</p>
          <div className="footer-stats">
            <span>📊 111 tests passing</span>
            <span>📦 16,000+ lines of code</span>
            <span>🚀 Ready to ship</span>
          </div>
        </div>
      </footer>
    </div>
  );
}

export default LandingPage;
