/**
 * Artifacts Panel - View AI-generated content
 * 
 * Shows code, designs, and content generated by AI employees.
 */

import { useState } from 'react';
import { useGameStore } from '../store/gameStore';
import type { TaskArtifact, Task } from '../types';
import './ArtifactsPanel.css';

// Syntax highlighting (simple version)
function CodeBlock({ code, language }: { code: string; language?: string }) {
  const [copied, setCopied] = useState(false);
  
  const handleCopy = async () => {
    await navigator.clipboard.writeText(code);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };
  
  return (
    <div className="code-block">
      <div className="code-header">
        <span className="code-lang">{language || 'text'}</span>
        <button className="copy-btn" onClick={handleCopy}>
          {copied ? '✓ Copied' : '📋 Copy'}
        </button>
      </div>
      <pre className="code-content">
        <code>{code}</code>
      </pre>
    </div>
  );
}

// Single artifact card
function ArtifactCard({ artifact, task }: { artifact: TaskArtifact; task: Task }) {
  const [expanded, setExpanded] = useState(false);
  const { employees } = useGameStore();
  
  const creator = employees.find(e => e.id === artifact.createdBy);
  
  const typeIcons: Record<string, string> = {
    code: '💻',
    design: '🎨',
    copy: '📝',
    document: '📄',
    analysis: '📊',
  };
  
  return (
    <div className={`artifact-card type-${artifact.type} ${expanded ? 'expanded' : ''}`}>
      <div className="artifact-header" onClick={() => setExpanded(!expanded)}>
        <div className="artifact-info">
          <span className="artifact-icon">{typeIcons[artifact.type] || '📦'}</span>
          <div className="artifact-meta">
            <span className="artifact-title">{artifact.title}</span>
            <span className="artifact-task">from: {task.title}</span>
          </div>
        </div>
        <div className="artifact-actions">
          {artifact.filePath && (
            <span className="file-path" title={artifact.filePath}>
              📁 {artifact.filePath}
            </span>
          )}
          {creator && (
            <span className="creator">
              {creator.avatarEmoji} {creator.name}
            </span>
          )}
          {artifact.modelUsed && (
            <span className="model-tag">{artifact.modelUsed}</span>
          )}
          <span className="expand-icon">{expanded ? '▼' : '▶'}</span>
        </div>
      </div>
      
      {expanded && (
        <div className="artifact-content">
          {artifact.type === 'code' ? (
            <CodeBlock code={artifact.content} language={artifact.language} />
          ) : (
            <div className="text-content">{artifact.content}</div>
          )}
        </div>
      )}
    </div>
  );
}

// AI Work Queue status
function AIWorkStatus() {
  const { aiWorkQueue, aiWorkInProgress, aiSettings, tasks } = useGameStore();
  
  if (!aiSettings.enabled) {
    return (
      <div className="ai-status-banner disabled">
        <span className="status-icon">🤖</span>
        <span className="status-text">AI is disabled. Enable in Settings to generate real code.</span>
      </div>
    );
  }
  
  const queuedCount = aiWorkQueue.filter(w => w.status === 'queued').length;
  const currentTask = aiWorkInProgress 
    ? tasks.find(t => t.id === aiWorkInProgress)
    : null;
  
  return (
    <div className="ai-status-banner active">
      <span className="status-icon">🧠</span>
      <div className="status-info">
        {currentTask ? (
          <span className="current-work">
            <span className="spinner">⚙️</span>
            Working on: <strong>{currentTask.title}</strong>
          </span>
        ) : queuedCount > 0 ? (
          <span className="queued-work">
            {queuedCount} task{queuedCount > 1 ? 's' : ''} in AI queue
          </span>
        ) : (
          <span className="idle-status">AI ready - assign tasks to generate code</span>
        )}
      </div>
      <span className="model-info">
        Model: {aiSettings.model}
      </span>
    </div>
  );
}

// Main artifacts panel
export function ArtifactsPanel() {
  const { tasks } = useGameStore();
  const [filter, setFilter] = useState<'all' | 'code' | 'design' | 'copy'>('all');
  const [sortBy, setSortBy] = useState<'recent' | 'task'>('recent');
  
  // Gather all artifacts from tasks
  const allArtifacts: { artifact: TaskArtifact; task: Task }[] = tasks
    .flatMap(task => 
      task.artifacts.map(artifact => ({ artifact, task }))
    )
    .filter(({ artifact }) => 
      filter === 'all' || artifact.type === filter
    )
    .sort((a, b) => {
      if (sortBy === 'recent') {
        return b.artifact.createdAt - a.artifact.createdAt;
      }
      return a.task.title.localeCompare(b.task.title);
    });
  
  // Also show legacy codeGenerated content
  const legacyCode = tasks
    .filter(t => t.codeGenerated && (filter === 'all' || filter === 'code'))
    .map(task => ({
      artifact: {
        id: `legacy-${task.id}`,
        type: 'code' as const,
        title: `Generated code for ${task.title}`,
        content: task.codeGenerated!,
        language: 'typescript',
        createdAt: task.completedAt || task.createdAt,
        createdBy: task.assigneeId || '',
      },
      task,
    }));
  
  const allItems = [...allArtifacts, ...legacyCode];
  
  // Stats
  const stats = {
    total: allItems.length,
    code: allItems.filter(i => i.artifact.type === 'code').length,
    design: allItems.filter(i => i.artifact.type === 'design').length,
    copy: allItems.filter(i => i.artifact.type === 'copy').length,
  };
  
  return (
    <div className="artifacts-panel">
      <AIWorkStatus />
      
      <div className="artifacts-header">
        <div className="header-left">
          <h2>📦 Generated Artifacts</h2>
          <div className="artifacts-stats">
            <span>{stats.total} total</span>
            <span>💻 {stats.code}</span>
            <span>🎨 {stats.design}</span>
            <span>📝 {stats.copy}</span>
          </div>
        </div>
        {stats.code > 0 && (
          <button 
            className="preview-btn"
            onClick={() => useGameStore.getState().setScreen('preview')}
          >
            👁️ Live Preview
          </button>
        )}
      </div>
      
      <div className="artifacts-filters">
        <div className="filter-group">
          <button 
            className={filter === 'all' ? 'active' : ''} 
            onClick={() => setFilter('all')}
          >
            All
          </button>
          <button 
            className={filter === 'code' ? 'active' : ''} 
            onClick={() => setFilter('code')}
          >
            💻 Code
          </button>
          <button 
            className={filter === 'design' ? 'active' : ''} 
            onClick={() => setFilter('design')}
          >
            🎨 Design
          </button>
          <button 
            className={filter === 'copy' ? 'active' : ''} 
            onClick={() => setFilter('copy')}
          >
            📝 Copy
          </button>
        </div>
        
        <div className="sort-group">
          <select value={sortBy} onChange={e => setSortBy(e.target.value as 'recent' | 'task')}>
            <option value="recent">Most Recent</option>
            <option value="task">By Task</option>
          </select>
        </div>
      </div>
      
      <div className="artifacts-list">
        {allItems.length === 0 ? (
          <div className="empty-state">
            <span className="empty-icon">📭</span>
            <h3>No artifacts yet</h3>
            <p>Assign tasks to employees with AI enabled to generate code, designs, and content.</p>
          </div>
        ) : (
          allItems.map(({ artifact, task }) => (
            <ArtifactCard key={artifact.id} artifact={artifact} task={task} />
          ))
        )}
      </div>
    </div>
  );
}

export default ArtifactsPanel;
