/**
 * Save Panel - Push generated code to GitHub
 */

import { useState, useEffect } from 'react';
import { useGameStore } from '../store/gameStore';
import { githubService } from '../lib/github';
import { useGitHub } from '../lib/github/useGitHub';
import './SavePanel.css';

export function SavePanel({
  isOpen,
  onClose,
}: {
  isOpen: boolean;
  onClose: () => void;
}) {
  const { tasks, project } = useGameStore();
  const { user, isAuthenticated, oauthConfigured, login, logout, getRepos } = useGitHub();
  
  const [repos, setRepos] = useState<Array<{ name: string; full_name: string; private: boolean }>>([]);
  const [selectedRepo, setSelectedRepo] = useState('');
  const [branch, setBranch] = useState('founder-mode');
  const [isPushing, setIsPushing] = useState(false);
  const [result, setResult] = useState<{ success: boolean; message: string } | null>(null);
  const [selectedFiles, setSelectedFiles] = useState<Set<string>>(new Set());
  const [loadingRepos, setLoadingRepos] = useState(false);

  // Get completed tasks with generated code
  const completedTasks = tasks.filter(t => t.status === 'done' && t.codeGenerated);
  
  // Generate file structure from completed tasks
  const generatedFiles = completedTasks.map(task => {
    const fileName = task.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');
    
    const extension = task.type === 'design' ? '.css' : 
                      task.type === 'marketing' ? '.md' : '.tsx';
    
    const folder = task.type === 'design' ? 'src/styles/' :
                   task.type === 'marketing' ? 'content/' :
                   task.type === 'bug' ? 'src/fixes/' :
                   'src/components/';
    
    return {
      id: task.id,
      path: `${folder}${fileName}${extension}`,
      content: task.codeGenerated || '',
      title: task.title,
      type: task.type,
    };
  });

  // Load repos when authenticated
  useEffect(() => {
    if (isAuthenticated && isOpen) {
      setLoadingRepos(true);
      getRepos().then(r => {
        setRepos(r);
        setLoadingRepos(false);
      });
    }
  }, [isAuthenticated, isOpen, getRepos]);

  // Configure github service when repo selected
  useEffect(() => {
    if (user && selectedRepo) {
      const [owner, repo] = selectedRepo.split('/');
      githubService.configure({
        token: user.token,
        owner,
        repo,
        branch,
      });
    }
  }, [user, selectedRepo, branch]);

  // Push to GitHub
  const pushToGitHub = async () => {
    if (!isAuthenticated || !selectedRepo) {
      setResult({ success: false, message: 'Select a repository first' });
      return;
    }

    const filesToPush = generatedFiles.filter(f => selectedFiles.has(f.id));
    if (filesToPush.length === 0) {
      setResult({ success: false, message: 'Select at least one file to push' });
      return;
    }

    setIsPushing(true);
    setResult(null);

    const commitMessage = `[Founder Mode] Add ${filesToPush.length} generated files

Project: ${project?.name || 'Unknown'}

Files:
${filesToPush.map(f => `- ${f.path}`).join('\n')}

Generated by Founder Mode 🚀`;

    const pushResult = await githubService.pushFiles(
      filesToPush.map(f => ({ path: f.path, content: f.content })),
      commitMessage
    );

    setIsPushing(false);
    setResult({
      success: pushResult.success,
      message: pushResult.success
        ? `✅ Pushed ${filesToPush.length} files! View at ${pushResult.url}`
        : `❌ ${pushResult.error || 'Failed to push'}`,
    });
  };

  // Select all files
  const selectAll = () => {
    setSelectedFiles(new Set(generatedFiles.map(f => f.id)));
  };

  // Toggle file selection
  const toggleFile = (id: string) => {
    const newSelected = new Set(selectedFiles);
    if (newSelected.has(id)) {
      newSelected.delete(id);
    } else {
      newSelected.add(id);
    }
    setSelectedFiles(newSelected);
  };

  // Select all on mount
  useEffect(() => {
    setSelectedFiles(new Set(generatedFiles.map(f => f.id)));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (!isOpen) return null;

  return (
    <div className="save-panel-overlay" onClick={onClose}>
      <div className="save-panel" onClick={e => e.stopPropagation()}>
        <div className="save-header">
          <h2>💾 Save to GitHub</h2>
          <button className="close-btn" onClick={onClose}>×</button>
        </div>

        <div className="save-body">
          {/* GitHub Auth */}
          <div className="config-section">
            <h3>🔗 GitHub Connection</h3>
            
            {!isAuthenticated ? (
              <div className="auth-prompt">
                {oauthConfigured ? (
                  <>
                    <p>Connect your GitHub account to push generated code directly to your repos.</p>
                    <button className="github-login-btn" onClick={login}>
                      <svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor">
                        <path d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0024 12c0-6.63-5.37-12-12-12z"/>
                      </svg>
                      Sign in with GitHub
                    </button>
                  </>
                ) : (
                  <p className="oauth-warning">
                    ⚠️ GitHub OAuth not configured on server. Set GITHUB_CLIENT_ID and GITHUB_CLIENT_SECRET env vars.
                  </p>
                )}
              </div>
            ) : (
              <div className="auth-connected">
                <div className="user-info">
                  {user?.avatar_url && (
                    <img src={user.avatar_url} alt={user.login} className="user-avatar" />
                  )}
                  <span className="user-name">{user?.login}</span>
                  <button className="logout-btn" onClick={logout}>Logout</button>
                </div>
                
                <div className="config-row">
                  <label>Repository</label>
                  <select 
                    value={selectedRepo} 
                    onChange={e => setSelectedRepo(e.target.value)}
                    disabled={loadingRepos}
                  >
                    <option value="">
                      {loadingRepos ? 'Loading repos...' : 'Select a repository'}
                    </option>
                    {repos.map(repo => (
                      <option key={repo.full_name} value={repo.full_name}>
                        {repo.private ? '🔒 ' : ''}{repo.full_name}
                      </option>
                    ))}
                  </select>
                </div>
                
                <div className="config-row">
                  <label>Branch</label>
                  <input
                    type="text"
                    value={branch}
                    onChange={e => setBranch(e.target.value)}
                    placeholder="founder-mode"
                  />
                </div>
              </div>
            )}
          </div>

          {/* File List */}
          <div className="files-section">
            <div className="files-header">
              <h3>📁 Generated Files ({generatedFiles.length})</h3>
              <button className="select-all-btn" onClick={selectAll}>
                Select All
              </button>
            </div>
            
            {generatedFiles.length === 0 ? (
              <div className="no-files">
                <p>No generated code yet!</p>
                <p>Complete tasks to generate code that can be pushed to GitHub.</p>
              </div>
            ) : (
              <div className="file-list">
                {generatedFiles.map(file => (
                  <div 
                    key={file.id}
                    className={`file-item ${selectedFiles.has(file.id) ? 'selected' : ''}`}
                    onClick={() => toggleFile(file.id)}
                  >
                    <input
                      type="checkbox"
                      checked={selectedFiles.has(file.id)}
                      onChange={() => toggleFile(file.id)}
                    />
                    <span className="file-icon">
                      {file.type === 'design' ? '🎨' : 
                       file.type === 'marketing' ? '📝' : 
                       file.type === 'bug' ? '🐛' : '📄'}
                    </span>
                    <span className="file-path">{file.path}</span>
                    <span className="file-title">{file.title}</span>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Result Message */}
          {result && (
            <div className={`result-message ${result.success ? 'success' : 'error'}`}>
              {result.message}
            </div>
          )}
        </div>

        <div className="save-footer">
          <button className="cancel-btn" onClick={onClose}>
            Cancel
          </button>
          <button
            className="push-btn"
            onClick={pushToGitHub}
            disabled={!isAuthenticated || !selectedRepo || selectedFiles.size === 0 || isPushing}
          >
            {isPushing ? '⏳ Pushing...' : `🚀 Push ${selectedFiles.size} Files`}
          </button>
        </div>
      </div>
    </div>
  );
}

export default SavePanel;
