/**
 * Save Panel - Push generated code to GitHub
 */

import { useState, useEffect } from 'react';
import { useGameStore } from '../store/gameStore';
import { githubService } from '../lib/github';
import './SavePanel.css';

export function SavePanel({
  isOpen,
  onClose,
}: {
  isOpen: boolean;
  onClose: () => void;
}) {
  const { tasks, project } = useGameStore();
  
  const [githubToken, setGithubToken] = useState('');
  const [repoUrl, setRepoUrl] = useState('');
  const [branch, setBranch] = useState('founder-mode');
  const [isConnected, setIsConnected] = useState(false);
  const [isPushing, setIsPushing] = useState(false);
  const [result, setResult] = useState<{ success: boolean; message: string } | null>(null);
  const [selectedFiles, setSelectedFiles] = useState<Set<string>>(new Set());

  // Get completed tasks with generated code
  const completedTasks = tasks.filter(t => t.status === 'done' && t.codeGenerated);
  
  // Generate file structure from completed tasks
  const generatedFiles = completedTasks.map(task => {
    const fileName = task.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '');
    
    const extension = task.type === 'design' ? '.css' : 
                      task.type === 'marketing' ? '.md' : '.tsx';
    
    const folder = task.type === 'design' ? 'src/styles/' :
                   task.type === 'marketing' ? 'content/' :
                   task.type === 'bug' ? 'src/fixes/' :
                   'src/components/';
    
    return {
      id: task.id,
      path: `${folder}${fileName}${extension}`,
      content: task.codeGenerated || '',
      title: task.title,
      type: task.type,
    };
  });

  // Parse repo URL
  const parseRepoUrl = (url: string) => {
    const match = url.match(/github\.com[/:]([^/]+)\/([^/.]+)/);
    if (match) {
      return { owner: match[1], repo: match[2] };
    }
    // Try owner/repo format
    const parts = url.split('/').filter(Boolean);
    if (parts.length >= 2) {
      return { owner: parts[parts.length - 2], repo: parts[parts.length - 1] };
    }
    return null;
  };

  // Test connection
  const testConnection = async () => {
    const parsed = parseRepoUrl(repoUrl);
    if (!parsed || !githubToken) {
      setResult({ success: false, message: 'Enter a valid repo URL and token' });
      return;
    }

    githubService.configure({
      token: githubToken,
      owner: parsed.owner,
      repo: parsed.repo,
      branch,
    });

    const test = await githubService.testConnection();
    setIsConnected(test.success);
    setResult({
      success: test.success,
      message: test.success ? `Connected to ${parsed.owner}/${parsed.repo}` : (test.error || 'Failed to connect'),
    });
  };

  // Push to GitHub
  const pushToGitHub = async () => {
    if (!isConnected) {
      setResult({ success: false, message: 'Not connected to GitHub' });
      return;
    }

    const filesToPush = generatedFiles.filter(f => selectedFiles.has(f.id));
    if (filesToPush.length === 0) {
      setResult({ success: false, message: 'Select at least one file to push' });
      return;
    }

    setIsPushing(true);
    setResult(null);

    const commitMessage = `[Founder Mode] Add ${filesToPush.length} generated files

Project: ${project?.name || 'Unknown'}

Files:
${filesToPush.map(f => `- ${f.path}`).join('\n')}

Generated by Founder Mode 🚀`;

    const pushResult = await githubService.pushFiles(
      filesToPush.map(f => ({ path: f.path, content: f.content })),
      commitMessage
    );

    setIsPushing(false);
    setResult({
      success: pushResult.success,
      message: pushResult.success
        ? `✅ Pushed ${filesToPush.length} files! View at ${pushResult.url}`
        : `❌ ${pushResult.error || 'Failed to push'}`,
    });
  };

  // Select all files
  const selectAll = () => {
    setSelectedFiles(new Set(generatedFiles.map(f => f.id)));
  };

  // Toggle file selection
  const toggleFile = (id: string) => {
    const newSelected = new Set(selectedFiles);
    if (newSelected.has(id)) {
      newSelected.delete(id);
    } else {
      newSelected.add(id);
    }
    setSelectedFiles(newSelected);
  };

  // Select all on mount
  useEffect(() => {
    setSelectedFiles(new Set(generatedFiles.map(f => f.id)));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  if (!isOpen) return null;

  return (
    <div className="save-panel-overlay" onClick={onClose}>
      <div className="save-panel" onClick={e => e.stopPropagation()}>
        <div className="save-header">
          <h2>💾 Save to GitHub</h2>
          <button className="close-btn" onClick={onClose}>×</button>
        </div>

        <div className="save-body">
          {/* GitHub Config */}
          <div className="config-section">
            <h3>🔗 GitHub Connection</h3>
            <div className="config-row">
              <label>Repository URL</label>
              <input
                type="text"
                value={repoUrl}
                onChange={e => setRepoUrl(e.target.value)}
                placeholder="github.com/username/repo or username/repo"
              />
            </div>
            <div className="config-row">
              <label>Personal Access Token</label>
              <input
                type="password"
                value={githubToken}
                onChange={e => setGithubToken(e.target.value)}
                placeholder="ghp_..."
              />
            </div>
            <div className="config-row">
              <label>Branch</label>
              <input
                type="text"
                value={branch}
                onChange={e => setBranch(e.target.value)}
                placeholder="founder-mode"
              />
            </div>
            <button 
              className="test-btn"
              onClick={testConnection}
              disabled={!repoUrl || !githubToken}
            >
              {isConnected ? '✅ Connected' : '🔌 Test Connection'}
            </button>
          </div>

          {/* File List */}
          <div className="files-section">
            <div className="files-header">
              <h3>📁 Generated Files ({generatedFiles.length})</h3>
              <button className="select-all-btn" onClick={selectAll}>
                Select All
              </button>
            </div>
            
            {generatedFiles.length === 0 ? (
              <div className="no-files">
                <p>No generated code yet!</p>
                <p>Complete tasks to generate code that can be pushed to GitHub.</p>
              </div>
            ) : (
              <div className="file-list">
                {generatedFiles.map(file => (
                  <div 
                    key={file.id}
                    className={`file-item ${selectedFiles.has(file.id) ? 'selected' : ''}`}
                    onClick={() => toggleFile(file.id)}
                  >
                    <input
                      type="checkbox"
                      checked={selectedFiles.has(file.id)}
                      onChange={() => toggleFile(file.id)}
                    />
                    <span className="file-icon">
                      {file.type === 'design' ? '🎨' : 
                       file.type === 'marketing' ? '📝' : 
                       file.type === 'bug' ? '🐛' : '📄'}
                    </span>
                    <span className="file-path">{file.path}</span>
                    <span className="file-title">{file.title}</span>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* Result Message */}
          {result && (
            <div className={`result-message ${result.success ? 'success' : 'error'}`}>
              {result.message}
            </div>
          )}
        </div>

        <div className="save-footer">
          <button className="cancel-btn" onClick={onClose}>
            Cancel
          </button>
          <button
            className="push-btn"
            onClick={pushToGitHub}
            disabled={!isConnected || selectedFiles.size === 0 || isPushing}
          >
            {isPushing ? '⏳ Pushing...' : `🚀 Push ${selectedFiles.size} Files`}
          </button>
        </div>
      </div>
    </div>
  );
}

export default SavePanel;
